apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::410030467528:role/UdacityFlaskDeployCBKubectlRole
username: build      
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: <arn:aws:iam::410030467528:user/admin>
      username: <admin>
      groups:
        - <system:masters>
    - userarn: <arn:aws:iam:410030467528::user/akdab>
      username: akdab
      groups:
        - <system:masters>